[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["@google/genai", "@getbrevo/brevo", "stripe", "pdf-parse"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
